title: "progress-report-afedie"
output: html_document
date: "2024-12-04"


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Anna's Lab Progress
### Data Cleaning

```{r}
library(tidyverse)

#Hall of Fame Data Table
library(Lahman)
head(HallOfFame, 3)

#Storing Data
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2024.shtml"
html <- read_html(url)
tables <- html_table(html)

#Viewing Data
head(tables[[1]], 3)

#Correcting Variables Names in Line 1 for Data Table
data <- tables[[1]]
actual_col_names <- data[1, ]
colnames(data) <- actual_col_names
data <- data[-1, ]
head(data, 3)

#Checking to Make Sure all Votes are Numeric Variables
data$Votes <- as.numeric(data$Votes)

#Deleting Unnecessary Columns
data <- data %>% select(-c(6:39))
data <- data %>% select(-c(`Rk`))
data <- data %>% select(-c(`YoB`))
data <- data %>% select(-c(`%vote`))

#Fixing Player Names
data <- data %>%
  mutate(Name = gsub("^X-", "", Name))

data <- data %>% rename(playerID = Name)

#Creating New Column if they are inducted or Not + Column YearID
data1 <- data %>% mutate(
  yearID = 2024,
  votedBy = "BBWAA",
  ballots = 385,
  needed = 289,
  inducted = ifelse(Votes>=289, "Y", "N"),
  category = NA, # don't know yet
  needed_note = NA
) %>% rename(
  votes = Votes)
  
#Merging Tables
data1 <- data1 %>% select(colnames(HallOfFame))
Hof <- rbind(data1, HallOfFame)

```



