---
title: "Lab 4 report"
author: "Ben McGuire"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown

Lahmen Hall of Fame Table
```{r}
library(Lahman)
head(HallOfFame, 3)
```

Hall of Fame Graph
```{r}
library(dplyr)
library(ggplot2)

HallOfFame %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2022))

View(HallOfFame)
```

CSV
```{r}

write.csv(HallOfFame, "HallOfFame.csv", row.names = FALSE)

```


Scrape Baseball Reference
```{r}

library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2024.shtml"
html <- read_html(url)
tables <- html_table(html)

View(tables[[1]])
```


Variable Names in Line 1
```{r}

data <- tables[[1]]
actual_col_names <- data[1, ]
colnames(data) <- actual_col_names
data <- data[-1, ]
head(data, 3)

```



Check Variable Types
```{r}

data$Votes <- as.numeric(data$Votes)

```


Functions needed
```{r}

data <- data %>% select(-c(6:39))
data <- data %>% select(-c(`Rk`))
data <- data %>% select(-c(`YoB`))
data <- data %>% select(-c(`%vote`))


```


Player Names
```{r}
data <- data %>%
  mutate(Name = gsub("^X-", "", Name))

data <- data %>% rename(playerID = Name)

```


New Column
```{r}

data1 <- data %>% mutate(
  yearID = 2024,
  votedBy = "BBWAA",
  ballots = 385,
  needed = 289,
  inducted = ifelse(Votes>=289, "Y", "N"),
  category = NA, # don't know yet
  needed_note = NA
) %>% rename(
  votes = Votes)

```


Merging Tables
```{r}

data1 <- data1 %>% select(colnames(HallOfFame))
Hof <- rbind(data1, HallOfFame)

```
