---
title: "progress-report-katiekeck"
author: "Kathryn Keck"
date: "2024-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install packages needed

```{r}
install.packages("Lahman")
library(Lahman)
install.packages("rvest")
library(rvest)
library(dplyr)
library(stringr)

head(HallOfFame)
```
Get the data from the web

```{r}
url <- "https://www.baseball-reference.com/awards/hof_2024.shtml"

webpage <- read_html(url)

hof_table <- webpage %>%
  html_table(fill = TRUE) %>%
  .[[1]]

head(hof_table)
```

Clean the data
```{r}
colnames(hof_table) <- hof_table[1, ]
hof_table <- hof_table[-1, ]
colnames(hof_table)

#add year id as 2024
hof_table$yearID <- 2024

#make column names same as HallOfFame data set
cleaned_data <- hof_table %>%
  select(Name, Votes, `%vote`, yearID) %>%
  rename(
    playerID = Name,
    votes = Votes,
    percent = `%vote`,
    yearID = yearID
  ) %>%
  #create inducted column
  mutate(
    percent = as.numeric(str_replace(percent, "%", "")),
    inducted = ifelse(percent >= 75, "Y", "N"),
    votedBy = "BBWAA"
  )

head(cleaned_data)

```
Merge the two data frames
```{r}
hall_of_fame <- HallOfFame %>%
  select(playerID, yearID, inducted) 

cleaned_data <- cleaned_data %>%
  select(playerID, yearID, inducted)

combined_data <- rbind(hall_of_fame, cleaned_data)

write.csv(combined_data, file="combined_data.csv", row.names = FALSE)

```

